import os

env = Environment(ENV = {'PATH' : os.environ['PATH'],
                         'TERM' : os.environ['TERM'],
                         'HOME' : os.environ['HOME']})

baseflags = ""
CFLAGS = "-fno-common -Wall -I../include {} -O0 -g".format(baseflags).split()
#CCFLAGS = CFLAGS + [ "-std=c++11" ]
LINKFLAGS = "{} -lGL -lGLU -lSDL2 -L.. -lsplat -g".format(baseflags).split()
CPPPATH = [ "#include",
			"/usr/include/SDL2" ]

env.Append(CFLAGS=CFLAGS)
#env.Append(CCFLAGS=CCFLAGS)
env.Append(LINKFLAGS=LINKFLAGS)
env.Append(CPPPATH=CPPPATH)

test_sources = [ "test.c"]

env.Program(target = "test", source = test_sources)

